# Generated by Django 3.1.7 on 2021-03-04 04:37

import apptrakzapi.helpers.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptrakzapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(null=True, storage=apptrakzapi.helpers.storage.OverwriteStorage(), upload_to='profile_images'),
        ),
    ]
