# Generated by Django 3.1.7 on 2021-03-08 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptrakzapi', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('user', 'job'), name='unique_job_application_user'),
        ),
    ]
