# Generated by Django 3.1.7 on 2021-03-13 22:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apptrakzapi', '0006_auto_20210313_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationstatus',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apptrakzapi.application'),
        ),
        migrations.AlterField(
            model_name='applicationstatus',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apptrakzapi.status'),
        ),
        migrations.AlterField(
            model_name='companynote',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='companynote',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apptrakzapi.company'),
        ),
        migrations.AlterField(
            model_name='contactnote',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contactnote',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apptrakzapi.contact'),
        ),
        migrations.AlterField(
            model_name='jobcontact',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apptrakzapi.contact'),
        ),
        migrations.AlterField(
            model_name='jobcontact',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apptrakzapi.job'),
        ),
        migrations.AlterField(
            model_name='jobnote',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jobnote',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apptrakzapi.job'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apptrakzapi.profile'),
        ),
    ]
