# Generated by Django 3.1.7 on 2021-03-13 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apptrakzapi', '0007_auto_20210313_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='applicationstatus',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='apptrakzapi.status'),
        ),
    ]
