# Generated by Django 3.1.7 on 2021-03-13 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptrakzapi', '0008_auto_20210313_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcontact',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
