# Generated by Django 3.1.7 on 2021-03-13 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apptrakzapi', '0010_contact_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='deleted',
        ),
    ]
