# Generated by Django 3.1.7 on 2021-03-13 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptrakzapi', '0011_remove_contact_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
